##Function to plot roc curves from pROC generated by our RF Classifier
# Modification of my older function which takes the entire Ranger RF object
# NA for confLevel removes the confidence interval

ROC_plotter <- function(votes, key, title, randVotes = NA,  confLvl = 0.95, plot=T){
  require(pROC)
  require(ggplot2)
  
  #Gather the model's votes and average them
  modelVotes <- rowMeans(votes, na.rm = T)
  modelVotes <- data.frame(model = modelVotes, response = key)
  
  #Gather the random votes
  if(!all(is.na(randVotes))){
    randVotes <- rowMeans(randVotes, na.rm = T)
    randVotes <- data.frame(rand = randVotes, response = key)
  }
  
  #Make the model and save for output
  modelROC <- roc(response ~ model, modelVotes)
  output <- list(modelROC = modelROC)
  
  # Plot out the ROC
  if(plot){
    rocObj <- ggroc(modelROC, lwd=1) + labs(x='Specificity', y='Sensitivity', title = title)
    rocObj <- rocObj + geom_label(x = -.25, 
                                  y=0.25, 
                                  label = paste('AUC:', round(modelROC$auc, digits = 2)), 
                                  label.size = NA, 
                                  size = 5,
                                  parse = FALSE)
    rocObj <- homogenizePlots(rocObj)
    rocObj <- rocObj + coord_cartesian(xlim=c(1, 0), ylim=c(0, 1))
    plot(rocObj)
  }
  return(output)
}

